packages:
    - ./package
    - ./test
    - ./examples/*

autoInstallPeers: false
strictPeerDependencies: false

allowBuilds:
    esbuild: true

catalogs:
    example:
        rolldown: ^1.1.4

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/*"
